### ISSUE TITLE
Release or tag

### ISSUE THREAD

**Issue by bebatut** [chengyuan/reago-1.1#5]
Hi,

I'm developing a wrapper to integrate reago in Galaxy. In this wrapper, reago code is downloaded. To help reproductibility, the downloaded code must be identical each time. 
Is it possible to have a release or at least a tag of the repository?
Thanks,

Bérénice

**Comment by chengyuan** [comment]
just created a tag, 'release-2015.12.18'

**Comment by bebatut** [comment]
Thanks :)
